/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import thread.ServerThread;

/**
 *
 * @author Dudat
 */
public class FMain extends javax.swing.JFrame {
    private ServerThread serverThread;
    /**
     * Creates new form FMain
     */
    public FMain() {
        initComponents();
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStatusPlaceHolder = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        lblErrorMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblStatusPlaceHolder.setText("Status:");

        lblStatus.setText("jLabel1");

        btnStart.setText("Start server");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStop.setText("Stop server");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStatusPlaceHolder)
                        .addGap(29, 29, 29)
                        .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblErrorMsg)
                .addGap(175, 175, 175))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatusPlaceHolder)
                    .addComponent(lblStatus))
                .addGap(18, 18, 18)
                .addComponent(btnStart)
                .addGap(18, 18, 18)
                .addComponent(btnStop)
                .addGap(39, 39, 39)
                .addComponent(lblErrorMsg)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        if (serverThread == null || serverThread.getServerSocket() == null || serverThread.getServerSocket().isClosed() == true) {
            try {
                serverThread = new ServerThread();
                serverThread.start();

                lblStatus.setText("Server is running!");
                lblStatus.setForeground(Color.DARK_GRAY);

                btnStart.setEnabled(false);
                btnStop.setEnabled(true);
            } catch (IOException ex) {
                lblStatus.setText("Error during server starting!");
                lblErrorMsg.setText(ex.getMessage());
                lblStatus.setForeground(Color.RED);
            }
        }
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        if (serverThread != null && serverThread.getServerSocket() != null || serverThread.getServerSocket().isClosed() == false) {
            try {
                serverThread.getServerSocket().close();
                btnStart.setEnabled(true);
                btnStop.setEnabled(false);
                lblStatus.setText("Server is closed. Start the server!");
            } catch (IOException ex) {
                lblErrorMsg.setText(ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnStopActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel lblErrorMsg;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatusPlaceHolder;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        btnStart.setEnabled(true);
        btnStop.setEnabled(false);
        setStatus("Start server");
    }
    
    private void setStatus(String msg){
        lblStatus.setText(msg);
    }
}
