/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.view;

import domain.Employee;
import java.awt.event.ActionListener;
import mvc.controller.MainScreenController;

/**
 *
 * @author Dudat
 */
public class FMainScreen extends javax.swing.JFrame {

    /**
     * Creates new form FClient
     */
    public FMainScreen(Employee emp) {
        initComponents();
        prepareForm(emp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNewClient = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        btnPreviewClient = new javax.swing.JButton();
        btnEditClient = new javax.swing.JButton();
        btnDeleteClient = new javax.swing.JButton();
        btnFindWoodProduct = new javax.swing.JButton();
        btnNewInvoice = new javax.swing.JButton();
        btnFindInvoice = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 100, 0, 0));
        setResizable(false);

        btnNewClient.setText("New client");

        lblUser.setText("jLabel1");

        btnPreviewClient.setText("Find client");

        btnEditClient.setText("Edit client");

        btnDeleteClient.setText("Delete client");

        btnFindWoodProduct.setText("Find wood product");

        btnNewInvoice.setText("New invoice");

        btnFindInvoice.setText("Find invoice");

        btnExit.setText("Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNewClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPreviewClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteClient, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFindWoodProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(btnNewInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFindInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUser)
                .addGap(178, 178, 178))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewClient)
                    .addComponent(btnFindWoodProduct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPreviewClient)
                    .addComponent(btnNewInvoice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditClient)
                    .addComponent(btnFindInvoice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteClient)
                    .addComponent(btnExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(lblUser)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteClient;
    private javax.swing.JButton btnEditClient;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFindInvoice;
    private javax.swing.JButton btnFindWoodProduct;
    private javax.swing.JButton btnNewClient;
    private javax.swing.JButton btnNewInvoice;
    private javax.swing.JButton btnPreviewClient;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables

    private void prepareForm(Employee emp) {
        lblUser.setText(emp.toString());
    }

    public void setNewClientListener(ActionListener listener) {
        btnNewClient.addActionListener(listener);
    }

    public void setPreviewClientListener(ActionListener listener) {
        btnPreviewClient.addActionListener(listener);
    }

    public void setEditClientListener(ActionListener listener) {
        btnEditClient.addActionListener(listener);
    }
    
    public void setDeleteClientListener(ActionListener listener){
        btnDeleteClient.addActionListener(listener);
    }

    public void setPreviewWoodProductListener(ActionListener listener) {
        btnFindWoodProduct.addActionListener(listener);
    }

    public void setNewInvoiceListener(ActionListener listener) {
        btnNewInvoice.addActionListener(listener);
    }

    public void setPreviewInvoiceListener(ActionListener listener) {
        btnFindInvoice.addActionListener(listener);
    }

    public void setExitListener(ActionListener listener) {
        btnExit.addActionListener(listener);
    }
}
